; PlatformIO Project Configuration File
; Waveshare ESP32-S3-Touch-LCD 3.5B

[env:waveshare-s3-touch-lcd35]
board = waveshare_s3_touch_lcd_35
board_build.partitions = custom_16Mb.csv
build_flags =
	${env.build_flags}
	-Iboards/waveshare-s3-touch-lcd35
	-Os
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DSCREEN_WIDTH=480
	-DSCREEN_HEIGHT=320
	-DTFT_DRIVER=ILI9488
	-DHAS_TOUCH=1

lib_deps =
	${env.lib_deps}
	xylopyrographer/LiteLED@^1.2.0
