; PlatformIO Project Configuration File
; Waveshare ESP32-S3 Touch LCD 3.5B
; Display: 3.5" 320x480 SPI (ILI9488), Touch: AXS15231B capacitive I2C
; PMU: AXP2101, IMU: QMI8658, RTC: PCF85063, Audio: ES8311, IO Exp: TCA9554
; Flash: 16MB, PSRAM: 8MB

[env:waveshare-esp32s3-touch-lcd-35]
board = waveshare-esp32s3-touch-lcd-3.5
monitor_speed = 115200
board_build.partitions = custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_src_filter = ${env.build_src_filter} +<../boards/waveshare-esp32s3-touch-lcd-3.5>
build_flags =
	${env.build_flags}
	-Iboards/waveshare-esp32s3-touch-lcd-3.5
	-O2

	-DWAVESHARE_ESP32_S3_TOUCH_LCD_3_5=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DBOARD_HAS_PSRAM

	-DDEVICE_NAME='"Waveshare 3.5"'

lib_deps =
	${env.lib_deps}
	lovyan03/LovyanGFX@^1.1.16
